### ISSUE TITLE
[Design Question] How many operations should we batch

### ISSUE THREAD

**Issue by adamsitnik** [tmds/Tmds.LinuxAsync#19]
In the current implementation of sockets in dotnet/runtime we do the following thing:

1. run epoll wait
2. when epoll tells us that nonblocking IO is possible and socket queue is not empty, we pop the async operation and execute in on thread pool
3. when the first operation finishes and there is one more in the queue, we also dispatch it to thread pool thread:

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L1006

I am not sure why we do that, I assume that we hope that nonblocking IO is still possible and in case of `EAGAIN` the operation is not removed from the queue.

@tmds how many operations are you adding to the AIO batch when epoll tells us that nonblocking IO is possible?

I just wonder how to make sure, that we don't batch too much and get a blocking IO using AIO as the end result. I wonder if we could use some Linux setting that would tell us how many bytes we can read|write (to determine how many operations we can actually batch for a single socket)

**Comment by tmds** [comment]
dotnet/runtime implementation performs the read/write on the threadpool. The rationale is that doing read/writes of different sockets simultaneously on the threadpool is faster than serializing them on the epoll thread. And it avoids the issue where the epoll thread could be the bottleneck.

Benchmarks haven't shown it is faster. And multiple epoll threads is an alternative to avoid the bottleneck issue.

To allow batching, we're doing read/write on the epoll thread.

All events that were reported by epoll are put in a batch.
For example, for a send operation, this is where it gets added to the _batch_:
https://github.com/tmds/Tmds.LinuxAsync/blob/c6dd0a31f6360a73a3bbf400c94fed7102524c10/src/Tmds.LinuxAsync/AsyncSocketOperation.cs#L250-L254

Then anything added to the batch, gets executed on the epoll thread here:
https://github.com/tmds/Tmds.LinuxAsync/blob/c6dd0a31f6360a73a3bbf400c94fed7102524c10/src/Tmds.LinuxAsync/EPollAsyncEngine.EPollThread.cs#L122

Normally a `Socket.ReceiveAsync/SendAsync` is tried synchronously, and if it fails with `EAGAIN`, it becomes batcheable on the epoll thread. The `DeferSends`/`DeferReceives` options allow to defer the synchronous attempt to the epoll thread, so they can also be batched.

The AIO batch won't block. A socket operation that is part of the batch can return EAGAIN, and then we'll retry it in a next batch (after epoll told us the fd is ready).

We're batching operations of different sockets together. We can also batch a read and a write of a single socket. Multiple reads/writes on the same sockets isn't common, and aren't batched. They are tricky to batch because they are interdependent. For example, a send of 5 batched with a send of 3. If the first send only sent 4 out of 5 bytes, you want to send the remaining byte before doing the 3-byte send.

**Comment by adamsitnik** [comment]
> The AIO batch won't block. A socket operation that is part of the batch can return EAGAIN, and then we'll retry it in a next batch (after epoll told us the fd is ready).

Thanks for the response! This is exactly what I was looking for.

**Comment by tmds** [comment]
Some additional interesting things:

> All events that were reported by epoll are put in a batch.

Empty receives (as used by ASP.NET Core to know when a socket has data without providing a buffer), aren't batchable with Linux AIO.

https://github.com/tmds/Tmds.LinuxAsync/blob/c6dd0a31f6360a73a3bbf400c94fed7102524c10/src/Tmds.LinuxAsync/AsyncSocketOperation.cs#L116-L117

> The AIO batch won't block. A socket operation that is part of the batch can return EAGAIN

With AIO we're putting the sockets in non-blocking mode. With `io_uring` we can use blocking sockets. That's because `io_uring` supports cancelling blocking operations. I'm not sure this means we should use it with blocking sockets with `io_uring`. The `Socket` `sendfile` operation can't be performed with `io_uring` and needs a non-blocking socket.
